# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  trace_config = debug
  TestApp_config = debug
endif
ifeq ($(config),release)
  trace_config = release
  TestApp_config = release
endif
ifeq ($(config),public)
  trace_config = public
  TestApp_config = public
endif

PROJECTS := trace TestApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

trace:
ifneq (,$(trace_config))
	@echo "==== Building trace ($(trace_config)) ===="
	@${MAKE} --no-print-directory -C trace -f Makefile config=$(trace_config)
endif

TestApp: trace
ifneq (,$(TestApp_config))
	@echo "==== Building TestApp ($(TestApp_config)) ===="
	@${MAKE} --no-print-directory -C TestApp -f Makefile config=$(TestApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C trace -f Makefile clean
	@${MAKE} --no-print-directory -C TestApp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  public"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   trace"
	@echo "   TestApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"