#pragma once

#define MAX_SHADOW_SUN_LIGHTS 2
#define MAX_SHADOW_SPOT_LIGHTS 8
#define MAX_SHADOW_POINT_LIGHTS 5

#define MAX_BONE_PER_VERTEX 4
#define MAX_BONES_PER_MESH 256

#define MAX_QUAD_INSTANCE 512

#define MAX_RENDER_GRAPH 32

#define GENERIC_PARAMETER_SIZE 16

#define ANIMATION_CLIP_FILE_EXTENSION ".trcac"
#define ANIMATION_GRAPH_FILE_EXTENSION ".trcag"
#define PREFAB_FILE_EXTENSION ".trprf"
#define MATERIAL_FILE_EXTENSION ".trmat"
#define RENDER_PIPELINE_FILE_EXTENSION ".trpip"
#define SKELETON_FILE_EXTENSION ".trcsk"
#define SEQUENCE_FILE_EXTENSION ".trcsq"
#define SCENE_FILE_EXTENSION ".trscn"
#define HUMANOID_RIG_FILE_EXTENSION ".trhrig"
#define FEATURE_DB_FILE_EXTENSION ".trmmft"
#define MMT_INFO_FILE_EXTENSION ".trmminf"
#define PARTICLE_EFFECT_FILE_EXTENSION ".trpeff"
#define PARTICLE_GENERATOR_FILE_EXTENSION ".trpgen"
